package sharding

import (
	"bufio"
	"os"
	"strings"
	"testing"
)

// TestLiveShardParity checks our partition against Synapse's own, over every
// destination in a real database.
//
// This is the verification the whole shadow rests on. Every other comparison
// with the real sender assumes both are deciding about the same destinations;
// if the partitions differ at all, none of them mean anything -- and a wrong
// shard function still produces a uniform, stable, entirely plausible split, so
// nothing else would reveal it.
//
// The fixture is generated by Synapse's own code, not ours. Produce it with:
//
//	psql -h /var/sockets -U gofed_ro -d synapse-db -At \
//	  -c 'SELECT destination FROM destinations ORDER BY destination;' > dests.txt
//	docker cp dests.txt av-federation-sender-worker-1:/tmp/dests.txt
//	docker exec av-federation-sender-worker-1 python3 -c '
//	from hashlib import sha256
//	inst = ["av-federation-sender-worker-1", "av-federation-sender-worker-2"]
//	out = open("/tmp/py-shards.tsv", "w")
//	for line in open("/tmp/dests.txt"):
//	    d = line.rstrip("\n")
//	    if not d: continue
//	    h = sha256(d.encode("utf8")).digest()
//	    out.write(d + "\t" + inst[int.from_bytes(h, byteorder="little") % len(inst)] + "\n")
//	out.close()'
//	docker cp av-federation-sender-worker-1:/tmp/py-shards.tsv .
//
// Then run:
//
//	SHARD_PARITY_FILE=py-shards.tsv \
//	SHARD_INSTANCES=av-federation-sender-worker-1,av-federation-sender-worker-2 \
//	go test ./internal/sharding/ -run TestLiveShardParity -v
func TestLiveShardParity(t *testing.T) {
	path := os.Getenv("SHARD_PARITY_FILE")
	if path == "" {
		t.Skip("set SHARD_PARITY_FILE to a TSV of destination<TAB>instance generated by Synapse")
	}
	instances := strings.Split(os.Getenv("SHARD_INSTANCES"), ",")
	if len(instances) == 0 || instances[0] == "" {
		t.Fatal("set SHARD_INSTANCES to the comma-separated federation_sender_instances, in order")
	}

	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	c := New(instances)
	counts := map[string]int{}
	var checked, mismatched int

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		dest, want, ok := strings.Cut(line, "\t")
		if !ok {
			continue
		}
		got := c.GetInstance(dest)
		checked++
		counts[got]++
		if got != want {
			mismatched++
			if mismatched <= 10 {
				t.Errorf("%q: we say %q, Synapse says %q", dest, got, want)
			}
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if checked == 0 {
		t.Fatal("the parity file was empty")
	}
	if mismatched > 0 {
		t.Fatalf("%d of %d destinations are on the wrong shard", mismatched, checked)
	}
	t.Logf("%d destinations, identical partition; ours: %v", checked, counts)
}
