package sharding

import "testing"

// The expected values below were generated by running Synapse's own
// _get_instance against the same inputs, not written by hand:
//
//	cd /home/daedric/synapse && python3 -c '
//	from hashlib import sha256
//	def get(instances, key):
//	    if len(instances) == 1: return instances[0]
//	    h = sha256(key.encode("utf8")).digest()
//	    return instances[int.from_bytes(h, byteorder="little") % len(instances)]
//	...'
//
// Regenerate the same way if this ever needs extending. A hand-written table
// would only prove that the Go code agrees with whatever the author believed
// Synapse does, which is exactly the assumption under test.
var (
	two   = []string{"av-federation-sender-worker-1", "av-federation-sender-worker-2"}
	three = []string{"av-federation-sender-worker-1", "av-federation-sender-worker-2", "av-gofederation-worker-1"}
)

func TestGetInstanceMatchesSynapse(t *testing.T) {
	cases := []struct {
		dest  string
		want2 string
		want3 string
	}{
		{"matrix.org", "av-federation-sender-worker-2", "av-gofederation-worker-1"},
		{"aguiarvieira.pt", "av-federation-sender-worker-1", "av-federation-sender-worker-2"},
		{"maunium.net", "av-federation-sender-worker-1", "av-gofederation-worker-1"},
		{"t2bot.io", "av-federation-sender-worker-1", "av-federation-sender-worker-1"},
		{"element.io", "av-federation-sender-worker-2", "av-gofederation-worker-1"},
		{"beeper.com", "av-federation-sender-worker-2", "av-federation-sender-worker-1"},
		{"codestorm.net", "av-federation-sender-worker-1", "av-gofederation-worker-1"},
		{"keys.aguiarvieira.pt", "av-federation-sender-worker-1", "av-gofederation-worker-1"},
		{"example.com", "av-federation-sender-worker-2", "av-federation-sender-worker-1"},
		{"a", "av-federation-sender-worker-1", "av-federation-sender-worker-2"},
		// The empty key is not a destination Synapse would ever shard, but it
		// pins the boundary behaviour of the hash rather than of our guards.
		{"", "av-federation-sender-worker-2", "av-federation-sender-worker-2"},
		{"xn--9q8h.example", "av-federation-sender-worker-1", "av-gofederation-worker-1"},
		// Case matters: Synapse hashes the destination string as given and does
		// not normalise it, so these are distinct shards.
		{"UPPER.example.com", "av-federation-sender-worker-1", "av-gofederation-worker-1"},
		// Non-ASCII goes in as UTF-8, which is what Go's []byte(string) gives.
		{"é.example", "av-federation-sender-worker-2", "av-federation-sender-worker-2"},
	}

	c2, c3 := New(two), New(three)
	for _, tc := range cases {
		if got := c2.GetInstance(tc.dest); got != tc.want2 {
			t.Errorf("GetInstance(%q) with 2 instances = %q, want %q", tc.dest, got, tc.want2)
		}
		if got := c3.GetInstance(tc.dest); got != tc.want3 {
			t.Errorf("GetInstance(%q) with 3 instances = %q, want %q", tc.dest, got, tc.want3)
		}
	}
}

// TestBigEndianWouldDiffer guards the one mistake this package exists to avoid.
//
// Reading the digest big-endian produces a partition that is uniform, stable
// and completely wrong. Asserting that it differs from ours on at least one of
// these destinations means a future refactor cannot quietly flip the byte order
// and still pass the table above by coincidence.
func TestBigEndianWouldDiffer(t *testing.T) {
	c := New(two)
	differs := false
	for _, d := range []string{"matrix.org", "aguiarvieira.pt", "maunium.net", "element.io"} {
		if c.GetInstance(d) != bigEndianInstance(two, d) {
			differs = true
			break
		}
	}
	if !differs {
		t.Fatal("big-endian and little-endian agreed on every sample; the test data no longer distinguishes them")
	}
}

func TestSingleInstanceHandlesEverything(t *testing.T) {
	c := New([]string{"only"})
	for _, d := range []string{"matrix.org", "", "a"} {
		if got := c.GetInstance(d); got != "only" {
			t.Errorf("GetInstance(%q) = %q, want %q", d, got, "only")
		}
		if !c.ShouldHandle("only", d) {
			t.Errorf("ShouldHandle(only, %q) = false, want true", d)
		}
	}
}

// An unconfigured shard is somebody else's business, not an error: Synapse's
// should_handle returns False before _get_instance can raise.
func TestNoInstancesHandlesNothing(t *testing.T) {
	c := New(nil)
	if c.ShouldHandle("anyone", "matrix.org") {
		t.Error("ShouldHandle with no instances = true, want false")
	}
	if got := c.GetInstance("matrix.org"); got != "" {
		t.Errorf("GetInstance with no instances = %q, want empty", got)
	}
}

func TestShouldHandleAgreesWithGetInstance(t *testing.T) {
	c := New(three)
	for _, d := range []string{"matrix.org", "aguiarvieira.pt", "t2bot.io"} {
		owner := c.GetInstance(d)
		for _, inst := range three {
			want := inst == owner
			if got := c.ShouldHandle(inst, d); got != want {
				t.Errorf("ShouldHandle(%q, %q) = %v, want %v", inst, d, got, want)
			}
		}
	}
}

// New must copy: a caller reusing its slice must not be able to reshard us.
func TestNewCopiesInstances(t *testing.T) {
	src := []string{"a", "b"}
	c := New(src)
	before := c.GetInstance("matrix.org")
	src[0], src[1] = "z", "y"
	if after := c.GetInstance("matrix.org"); after != before {
		t.Errorf("mutating the caller's slice changed the shard: %q -> %q", before, after)
	}
	if got := c.Instances(); got[0] != "a" || got[1] != "b" {
		t.Errorf("Instances() = %v, want [a b]", got)
	}
}
